### ISSUE TITLE
Suspend loop after upgrade

### ISSUE THREAD

**Issue by slidinghotdog** [lxqt/lxqt-powermanagement#238] opened 2021-02-25 18:14 UTC
I was having some errors when compiling lxqt-panel then removed all lxqt packages and installed git versions from AUR, then after rebooting the system, first login it showed a lot of notifications about lxqt-powermanagement and suspended imediatelly. (all i could read from notifications was something about dbus, there were 10 or so notifications)

##### Expected Behavior

continue working as before

##### Current Behavior

suspends imediatelly after login and after waking (already fixed on my system, see below)

##### Possible Solution

switched to tty, removed `~./config/lxqt/lxqt-powermanagement.conf` and restarted sddm
##### Steps to Reproduce (for bugs)

~~Not sure if it will be reproducible but the previous setting was 100+ minutes idle to suspend (not sure of the values since i deleted the conf file)~~

- on Session Settings, disable "Lock screen before suspending/hibernating" (Don't know if this is related)

- Enable Idleness Watcher, set to suspend and set some time (tested on a VM 1 min and 120 min)

- remove lxqt, install latest git version (had to reinstall everything because of deps on liblxqt, lxqt-build-tools, etc), i used AUR and paru (AUR helper) but should be the same manually compiling on other distros

- Reboot

Or if already on latest git version u could replace `~/.config/lxqt/lxqt-powermanagement.conf` contents with:

```[General]
__userfile__=true
backlightIdleness=0
backlightIdlenessOnBatteryDischarging=true
enableBatteryWatcher=true
enableIdlenessBacklightWatcher=false
enableIdlenessWatcher=true
enableLidWatcher=false
idlenessAction=4
idlenessTime=@Variant(\0\0\0\xf\0\0\x3\xe8)
idlenessTimeSecs=7200
runCheckLevel=1
```

##### Context

I already fixed on my system so no need for support, but there's probably some error when getting the values from older config file, possibly from the change in #228, and it could cause issues on next release.

##### System Information

* Distribution & Version: Archlinux
* Kernel: 5.11.1-arch1-1
* Qt Version: qt5-base 5.15.2-5
* liblxqt Version: 0.16.0.18.g0eb9dc7-1 (git version from AUR in feb 24)
* lxqt-build-tools Version: 0.8.0.6.g17d975c-1 (git version from AUR in feb 24)
* Package version: upgrading from 0.16.0-1 (repo version) to 0.16.0.20.g231759d-1 (git version from AUR in feb 24)

EDIT: Also it's a desktop pc, so no battery/lid actions

**Comment by tsujan** [comment] 2021-02-26 07:08
> possibly from the change in #228

It had a problem but it was fixed by the contributor, after @palinek told him about it.

With your report, it may need a second check.

**Comment by slidinghotdog** [comment] 2021-03-01 00:10
Tested on a fresh install on virtualbox and the same thing happened, updated section "Steps to Reproduce (for bugs)" in first post

**Comment by tsujan** [comment] 2021-03-01 01:08
Tomorrow I'll reread the suspicious commit. Thanks for your report and comments!

**Comment by slidinghotdog** [comment] 2021-03-01 01:49
Alright, added old config file so if using git version u should be able to test just replacing the file

**Comment by tsujan** [comment] 2021-03-01 14:01
@slidinghotdog 
Your guess was right. The problem is in https://github.com/lxqt/lxqt-powermanagement/pull/228: it reads the legacy setting incorrectly. I'll make a PR.

**Comment by tsujan** [comment] 2021-03-01 15:20
@slidinghotdog
A probable fix is here: https://github.com/lxqt/lxqt-powermanagement/pull/239

Could you please test it as you did before? If you do and it works, please also test a few idle times. I set the minimum to 1 minute because a smaller idle time wasn't practical for shutdown/suspend/hibernation.

**Comment by slidinghotdog** [comment] 2021-03-01 20:46
Ok, the fix works, tested a few different values and had no problems.

**Comment by tsujan** [comment] 2021-03-01 20:57
Thank you so much for everything you did here!

**Comment by slidinghotdog** [comment] 2021-03-02 00:18
No problem, thanks for the quick response!

**Closed** 2021-03-08 05:22 UTC
